version: "3.9"

services:
  storage-api:
    container_name: REKA-Service-Storage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    env_file:
      - /var/www/reka-storage-api-application/.env
    restart: unless-stopped
